import Head from 'next/head'
import Layout from '@/components/Layout'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import Image from 'next/image'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
<main className='flex items-center text-dark w-full min-h-screen'>

<Layout className='pt=0'>

<div className="flex items-center justify-between w-full">
    
</div>

</Layout>



</main>
    </>
  )
}
